### ISSUE TITLE
use it to be a radius server?

### ISSUE THREAD

**Issue by Ethan-Yami** [LawnGnome/php-radius#1]
How to use the radius extension to develop a Radius server with Swoole extension?
Swoole PHP extension is TCP/UDP SERVER.

Could you give me some example or notice?
Thanks.

**Comment by lferro9000** [comment]
This extension is just a client. For a radius server, look at:

http://www.linuxplanet.com/linuxplanet/reports/7222/1

There may be new alternatives as the post is pretty old (7 years old).
